---
- name: Install httpd
  yum: "name={{ item }} state=present"
  with_items:
    - httpd

- name: Start httpd
  action: service name=httpd state=started enabled=yes

- name: Insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ httpd_port }}"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport {{ httpd_port }} -j ACCEPT"
  notify: Restart iptables
