---
- name: rbenv | install passenger
  shell: RBENV_ROOT={{ rbenv_root }} gem install passenger -v {{ passenger_version }}

- name: Install passenger dependency packages
  yum: "name={{ item }} state=present"
  with_items:
    - gcc
    - gcc-c++
    - curl-devel
    - openssl-devel
    - zlib-devel
    - httpd-devel

- name: Install passenger-install-apache2-module
  shell: passenger-install-apache2-module --auto creates={{ rbenv_root }}/versions/{{ ruby_version }}/passenger-{{ passenger_version }}/buildout/apache2/mod_passenger.so

- name: Generate passenger.conf file
  shell: passenger-install-apache2-module --snippet > /etc/httpd/conf.d/passenger.conf

- name: Restart httpd
  service: name=httpd state=restarted
